typography_spectrum: 0.07889
color:
  brandColors:
    - '#fafeff'
    - '#544033'
    - '#9eafbb'
    - '#6b7c88'
    - '#fd5c3b'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: George Matarazzo
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Photography
    id: 0014db15-63f1-4587-b089-7e1c94d228f8
    type: content
favicon: null
title: George Matarazzo Photography
purpose: []
