name: George Matarazzo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07889
title: George Matarazzo Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafeff'
    - '#544033'
    - '#9eafbb'
    - '#6b7c88'
    - '#fd5c3b'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
